### PR TITLE
Deploy registries on other chains (FTM, ARB, OPT)

### PR DESCRIPTION
**Pull request by penandlim**
Adds deploy scripts that will deploy MasterRegistry and PoolRegistry then register all live pools on Fantom, Arbitrum, and Optimism.

Optimism:
```
New deployments:
┌─────────┬──────────────────┬──────────────────────────────────────────────┐
│ (index) │        0         │                      1                       │
├─────────┼──────────────────┼──────────────────────────────────────────────┤
│    0    │  'PoolRegistry'  │ '0x4E1484607760118ebE2Ab07C0c71f1B4D9671e01' │
│    1    │ 'MasterRegistry' │ '0x0E510c9b20a5D136E75f7FD2a5F344BD98f9d875' │
└─────────┴──────────────────┴──────────────────────────────────────────────┘
```

Fantom: 

```
New deployments:
┌─────────┬──────────────────┬──────────────────────────────────────────────┐
│ (index) │        0         │                      1                       │
├─────────┼──────────────────┼──────────────────────────────────────────────┤
│    0    │  'PoolRegistry'  │ '0x88Cc4aA0dd6Cf126b00C012dDa9f6F4fd9388b17' │
│    1    │ 'MasterRegistry' │ '0x7003102c75587E8D29c56124060463Ef319407D0' │
└─────────┴──────────────────┴──────────────────────────────────────────────┘
```

Arbitrum:
```
New deployments:
┌─────────┬──────────────────┬──────────────────────────────────────────────┐
│ (index) │        0         │                      1                       │
├─────────┼──────────────────┼──────────────────────────────────────────────┤
│    0    │  'PoolRegistry'  │ '0x38262c17a06A6B3588d3E5b70dfa768C06bf4ef1' │
│    1    │ 'MasterRegistry' │ '0xaB94A2c0D8F044AA439A5654f06b5797928396cF' │
└─────────┴──────────────────┴──────────────────────────────────────────────┘
```

### CODE REVIEW

**Review by ug02fast — COMMENTED** [review]
is the `PoolRegistry copy.ts` naming intentional?

**Comment by penandlim** [comment]
Oops thats a typo will fix the titles.

Optimism:
```
New deployments:
┌─────────┬──────────────────┬──────────────────────────────────────────────┐
│ (index) │        0         │                      1                       │
├─────────┼──────────────────┼──────────────────────────────────────────────┤
│    0    │  'PoolRegistry'  │ '0x4E1484607760118ebE2Ab07C0c71f1B4D9671e01' │
│    1    │ 'MasterRegistry' │ '0x0E510c9b20a5D136E75f7FD2a5F344BD98f9d875' │
└─────────┴──────────────────┴──────────────────────────────────────────────┘
```

Need some gas on Fantom on Arbitrum for more deploys so will be bridging some eth/ gas tokens

**Review by nkrulikovsky — DISMISSED** [review]

**Comment by penandlim** [comment]
Deployed to Arbitrum.

**Review by nkrulikovsky — APPROVED** [review]
Awesome!

**Pull request merged**
